import type { NextPage } from 'next'
import { ImageContainer, IntroDescription, Main, BmwText, MlogoContainer, MainInformationContainer, PriceContainer, PriceInformation, PriceTitle, PowerInformationContainer, PowerInformation, PowerTitle, FuelTypeContainer, FuelTypeInformation, FuelTypeTitle, IntroContainer, GoToDetailsButton, FillTheSurveyButton, ButtonContainer } from '../styles/index.style'
import Head from 'next/head'
import Image from 'next/image'
import BMWM8 from '../public/BmwM8.jpg'
import {motion} from "framer-motion"
import Link from 'next/link'
const Home: NextPage = () => {
  const fadeIn = {
    hidden:{opacity:0},
    show:{
      opacity:1
    }, 
  }

  return (
    <div>
      <Head>
        <title>BMW</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main as={motion.div} initial={{width:0}} animate={{width:"100%"}} exit={{x:"100%", transition:{ease:"easeIn", duration:0.5}}}>
         <ImageContainer >
        <Image alt="an image" src={BMWM8} height={785}></Image>
      </ImageContainer>
        <IntroContainer as={motion.div} variants={fadeIn} initial="hidden" animate="show" transition={{duration:2}}>
          <BmwText>The M8</BmwText>
          <IntroDescription>NEW BMW M8 COUPE RANGE</IntroDescription>
            <ButtonContainer>
              <Link href="/Details">
              <GoToDetailsButton as={motion.span} whileHover={{border:"3px solid white"}}>See the details...</GoToDetailsButton>
              </Link>
              <Link href="/Survey">
              <FillTheSurveyButton as={motion.span} whileHover={{border:"3px solid white"}}>Fill the survey...</FillTheSurveyButton>
              </Link>
            </ButtonContainer>
        </IntroContainer>
        <MainInformationContainer variants={fadeIn} as={motion.div} initial="hidden" animate="show" transition={{delay:1}}>
          <PriceContainer>
            <PriceInformation>200,800$</PriceInformation>
            <PriceTitle>Price from</PriceTitle>
          </PriceContainer>
          <PowerInformationContainer>
            <PowerInformation>460kW[625 hp]</PowerInformation>      
              <PowerTitle>Power up</PowerTitle>
          </PowerInformationContainer>
          <FuelTypeContainer>
            <FuelTypeInformation>Gasoline</FuelTypeInformation>
            <FuelTypeTitle>Engine and Fuel Type</FuelTypeTitle>
          </FuelTypeContainer>
        </MainInformationContainer>
      </Main>
    </div>
  )
}

export default Home;
